### PR TITLE
Graph connected components

### PR DESCRIPTION
**Pull request by cmalinmayor**
Originally I tried to apply tests I had written for the mongo backend to the file backend. This revealed some bugs/unfinished features in the file backend that I either fixed, implemented, or made throw an error if you try to use an unimplemented feature.

### CODE REVIEW

**Comment by cmalinmayor** [comment]
I'm not sure why the connected component test failed - it passes locally. I'll try and figure that out and fix it. 
I can't get the read_blockwise tests to run locally (I get some IO Loop error) so I'm not inclined to debug the file read_blockwise error since that wasn't my main goal with this branch anyways - I can either take it out or leave it in as a failing test to remind us to fix it.
I see that the third failing test was already failing previously, so I won't touch that either.

**Comment by funkey** [comment]
The `IOLoop` error might come from an older version of tornado. We updated the `requirements.txt` a while back to prevent that, maybe you are still running on an older version?

**Comment by cmalinmayor** [comment]
Ah yes, it appears that luigi requires tornado < 5, and that was holding it back from upgrading in my conda environment. I can now run the failing test. Do you want me to debug why the test for reading blockwise from the file backend is failing, or are we moving away from the file backend and I should just delete it?

**Comment by funkey** [comment]
As discussed offline: The test for the file backend graph provider likely fails because of writes that are not chunk aligned. Please fix the test and add a note to the docstring reminding users that parallel writes are only save if chunk aligned.

**Comment by cmalinmayor** [comment]
There were actually two separate bugs being caught by this test case. One was a simple bug that I introduced in the __get_roi_filter function that checked which nodes were within a roi. The other was related to the way that numpy infers type when saving and then loading lists of numbers. If we saved an int id close to the upper range of np.uint64, numpy would infer a type of float64 when reading it back in from file. Then, casting this float to a np.uint64 results in a value of zero. Don't ask me why, I have no idea. If you cast the ids from int to np.uint64 before saving them, it reads them back in as uint64, resulting in the behavior we want. This probably isn't the most elegant solution, since non-id values will still exhibit the strange behavior. I'll need to get a deeper understanding of the factors at work to come up with something better.

**Pull request merged**
