### PR TITLE
unpark some of the parked tests. mainly related to graph providers

### PR DESCRIPTION
**Pull request by pattonw**
Tests run on both `FileGraphProvider` and `MongoGraphProvider`.
Mongographprovider tests are skipped if mongodb is not available.
many tests fail.
test_worker_pool not refactored. I'm not too familiar with how the `WorkerPool`, `Server`, `Context`, `TCPServer` etc. changed to know what tests might be relevant to keep.

### CODE REVIEW

**Comment by pattonw** [comment]
Tests that currently fail:
Not implemented errors for `FileGraphProvider`:
`tests/test_graph_attribute_functions.py::{all}[file]`. Attribute functions not implemented.
`tests/test_graph.py::test_graph_write_attributes[file]`. Attribute functions not implemented.
`tests/test_graph_connected_components[file]`. Connected components not implemented.

Other:
`tests/test_graph.py::test_graph_read_blockwise[file]`. Seems to hang forever. This seems more serious.

`test_multi_tasks.py`. `daisy` no longer has a `distribute` helper function. Not sure if we have any similar api where we can define a task and then request a subregion of that tasks total roi for computation.

**Comment by trivoldus28** [comment]
Do you think we should merge these unparked tests now or fix more tests before merging?

**Comment by pattonw** [comment]
I think we should go ahead and merge. I'm not going to have much time to fix the hanging test and the others are low priority I think.
Could always mark them as expected failures and make a note of them for anyone who has time/interest in fixing them

**Comment by trivoldus28** [comment]
@pattonw I think some of the tests you added back are failing? https://app.travis-ci.com/github/funkelab/daisy/builds/254352299

**Comment by pattonw** [comment]
Yes.
1) The `FileGraphProvider` api does not match the `MongoGraphProvider`. For example there's no support for filtering node and edge attributes when fetching a graph for a given roi. I'm not sure what the purpose of the `FileGraphProvider` is if it doesn't match the `MongoGraphProvider` since I don't expect anyone to use it for anything other than small tests. I think we can either mark these failures as expected and get around to updating the `FileGraphProvider` at some point or maybe just remove these tests and the `FileGraphProvider` class as a whole if it isn't used.
2) There is no longer a `distribute` helper function. `daisy` used to support setting up tasks and then requesting a sub-region to be computed. It seems this is no longer supported, so all of those tests fail. I think the options here are either mark as expected failures and add this functionality back in the future, or just get rid of these tests and ignore this functionality.
3) `read_blockwise` hangs forever. This should be fixed asap

**Comment by trivoldus28** [comment]
1. I'm actually using `FileGraphProvider` primarily for large scale deployments - it has much better performance. Let me see which tests are applicable and disable tests of unimplemented features.
2. Yes let's remove `distribute`
3. That should be fixed yea..

**Comment by pattonw** [comment]
Ok, I'll remove the tests related to distribute.
Good to know that the `FileGraphProvider` is fast. I've always defaulted to the Mongo version.

**Comment by pattonw** [comment]
closing since this has all been moved to `funlib.persistence`

**Pull request closed without merging**
